# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-18 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=5000)),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Oportunidades',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, help_text='Optional.', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Optional.', max_length=30, null=True)),
                ('email', models.EmailField(help_text='Required. Inform a valid email address.', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('relacionado', models.ManyToManyField(blank=True, related_name='_tipo_relacionado_+', to='bolsa.Tipo')),
            ],
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolsa.Tipo'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
