# Generated by Django 2.2.5 on 2019-09-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='relacionado',
            field=models.ManyToManyField(blank=True, related_name='_tipo_relacionado_+', to='bolsa.Tipo'),
        ),
    ]
