# Generated by Django 2.2.5 on 2019-09-14 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_auto_20190914_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bolsa.Tipo'),
            preserve_default=False,
        ),
    ]
