# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(default='Franco', help_text='Campo obligatorio', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Gómez', help_text='Campo Obligatorio', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', help_text='Campo Obligatorio', max_length=30),
            preserve_default=False,
        ),
    ]
