# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-18 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0005_oportunidad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='es_alumno',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='es_oferente',
            field=models.BooleanField(default=False),
        ),
    ]
