# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-19 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0006_auto_20190918_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
