# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-24 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0008_auto_20190923_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
